version: "2"

services:
  backend:
    container_name: backoffice_backend_prod
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=7000
    volumes:
      - ./src:/var/www/backend/src
      - ./test:/var/www/backend/test
      - ./uploads:/var/www/backend/uploads
    working_dir: /var/www/backend
    ports:
      - "7000:3000"
    links:
      - backoffice_db_postgres
      - redis
    depends_on:
      - backoffice_db_postgres
      - redis

  backoffice_db_postgres: # Example Service
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: backoffice_db_prod
    restart: always
    environment:
      TZ: '-03'
      PGTZ: '-03'
      POSTGRES_DB: backoffice_pp
      POSTGRES_USER: Nicholas
      POSTGRES_PASSWORD: minhasenha
      
    volumes:
      - backoffice_api_data_prod:/var/lib/postgresql/data
    
  redis: # Example Service
    container_name: backoffice_api_redis_prod
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - backoffice_api_redis_data_prod:/data

  adminer:
    container_name: 'backoffice_api_adminer_prod'
    image: adminer
    restart: always
    ports:
      - 7002:8080
    depends_on: 
      - backoffice_db_postgres

volumes:
  backoffice_api_data_prod:
  backoffice_api_redis_data_prod:

networks:
  default:
    external:
      name: backoffice_api
